version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/frontend
            - /frontend/node_modules
        container_name: next_frontend
        # restart: always
        ports:
            - 5000:5000
        env_file: .env
        command: yarn start
